# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

rcpp_process_batch <- function(raw_data, adds, indices, batch_start, calib_coefs = NULL, use_integer_intensity = FALSE, use_float_mz = FALSE) {
    .Call(`_rawsewage_rcpp_process_batch`, raw_data, adds, indices, batch_start, calib_coefs, use_integer_intensity, use_float_mz)
}

